import { Delivery } from '../types';

/**
 * Initial server dataset (Egyptian mock data): 6 pending, 1 delivered,
 * 1 failed. Amounts are EGP with two decimals; phones are Egyptian mobile
 * numbers in local format (01x xxxxxxxx).
 */
export function seedDeliveries(): Delivery[] {
  const now = new Date().toISOString();
  const base = {
    note: null,
    recipient_name: null,
    failure_reason: null,
    proof_attached: false,
    version: 1,
    updated_at: now,
  };
  return [
    {
      ...base,
      id: 1001,
      order_number: 'ORD-1001',
      customer_name: 'Ahmed Ali',
      phone: '01012345667',
      address: 'Nasr City, Abbas El Akkad St., Bldg 12, Apt 7, Cairo',
      amount_due: 350.0,
      payment_method: 'cash',
      status: 'pending',
      note: 'Ring the doorbell twice — customer has limited mobility',
    },
    {
      ...base,
      id: 1002,
      order_number: 'ORD-1002',
      customer_name: 'Mohamed Hassan',
      phone: '01123456778',
      address: 'Maadi, Street 9, Villa 24, Cairo',
      amount_due: 1250.0,
      payment_method: 'card',
      status: 'pending',
    },
    {
      ...base,
      id: 1003,
      order_number: 'ORD-1003',
      customer_name: 'Mostafa Ibrahim',
      phone: '01223456789',
      address: 'Heliopolis, Baghdad St., Bldg 8, Apt 3, Cairo',
      amount_due: 480.5,
      payment_method: 'cash',
      status: 'pending',
      note: 'Leave with the doorman (bawab) if no answer',
    },
    {
      ...base,
      id: 1004,
      order_number: 'ORD-1004',
      customer_name: 'Nour Adel',
      phone: '01098765432',
      address: 'New Cairo, Fifth Settlement, 90th St., Gate 2, Cairo',
      amount_due: 2799.99,
      payment_method: 'card',
      status: 'pending',
      note: 'Gated compound — call for the access code',
    },
    {
      ...base,
      id: 1005,
      order_number: 'ORD-1005',
      customer_name: 'Omar Farouk',
      phone: '01555334455',
      address: 'Dokki, Tahrir St., Bldg 21, Apt 10, Giza',
      amount_due: 620.0,
      payment_method: 'cash',
      status: 'pending',
    },
    {
      ...base,
      id: 1006,
      order_number: 'ORD-1006',
      customer_name: 'Mariam Sabry',
      phone: '01278345612',
      address: 'Mohandessin, Shehab St., Bldg 5, Roof, Giza',
      amount_due: 890.25,
      payment_method: 'card',
      status: 'pending',
    },
    {
      ...base,
      id: 1007,
      order_number: 'ORD-1007',
      customer_name: 'Khaled Mansour',
      phone: '01005556677',
      address: 'Smouha, Abu Qir St., Bldg 14, Alexandria',
      amount_due: 145.75,
      payment_method: 'cash',
      status: 'delivered',
      recipient_name: 'Khaled Mansour',
      note: 'Delivered to customer',
      proof_attached: true,
    },
    {
      ...base,
      id: 1008,
      order_number: 'ORD-1008',
      customer_name: 'Hanaa El-Sayed',
      phone: '01122334455',
      address: '6th of October City, 1st District, St. 14, Giza',
      amount_due: 1999.0,
      payment_method: 'card',
      status: 'failed',
      failure_reason: 'customer_unavailable',
      note: 'Called twice, no answer',
    },
  ];
}
