import { Delivery } from '../types';

/** Initial server dataset: 6 pending, 1 delivered, 1 failed. */
export function seedDeliveries(): Delivery[] {
  const now = new Date().toISOString();
  const base = {
    note: null,
    recipient_name: null,
    failure_reason: null,
    proof_attached: false,
    version: 1,
    updated_at: now,
  };
  return [
    {
      ...base,
      id: 1001,
      order_number: 'ORD-1001',
      customer_name: 'Ahmed Ali',
      phone: '55512345',
      address: 'Salmiya, Block 4, Street 12',
      amount_due: 18.75,
      payment_method: 'cash',
      status: 'pending',
      note: 'Ring doorbell twice — customer has limited mobility',
    },
    {
      ...base,
      id: 1002,
      order_number: 'ORD-1002',
      customer_name: 'Fatma Hassan',
      phone: '55523456',
      address: 'Hawally, Block 3, Street 5, Bldg 14',
      amount_due: 42.0,
      payment_method: 'card',
      status: 'pending',
    },
    {
      ...base,
      id: 1003,
      order_number: 'ORD-1003',
      customer_name: 'Yousef Al-Rashid',
      phone: '55534567',
      address: 'Farwaniya, Block 2, Avenue 7',
      amount_due: 9.5,
      payment_method: 'cash',
      status: 'pending',
      note: 'Leave with reception if no answer',
    },
    {
      ...base,
      id: 1004,
      order_number: 'ORD-1004',
      customer_name: 'Noura Al-Sabah',
      phone: '55545678',
      address: 'Jabriya, Block 1, Street 9',
      amount_due: 27.25,
      payment_method: 'card',
      status: 'pending',
    },
    {
      ...base,
      id: 1005,
      order_number: 'ORD-1005',
      customer_name: 'Bader Al-Mutairi',
      phone: '55556789',
      address: 'Salmiya, Block 7, Street 21',
      amount_due: 15.0,
      payment_method: 'cash',
      status: 'pending',
    },
    {
      ...base,
      id: 1006,
      order_number: 'ORD-1006',
      customer_name: 'Sarah Jenkins',
      phone: '55567890',
      address: 'Mahboula, Block 4, Street 2',
      amount_due: 33.5,
      payment_method: 'card',
      status: 'pending',
      note: 'Gated building — call for access code',
    },
    {
      ...base,
      id: 1007,
      order_number: 'ORD-1007',
      customer_name: 'Hamad Al-Azemi',
      phone: '55578901',
      address: 'Shuhada, Block 5, Street 8',
      amount_due: 12.25,
      payment_method: 'cash',
      status: 'delivered',
      recipient_name: 'Hamad Al-Azemi',
      note: 'Delivered to customer',
      proof_attached: true,
    },
    {
      ...base,
      id: 1008,
      order_number: 'ORD-1008',
      customer_name: 'Dana Al-Enezi',
      phone: '55589012',
      address: 'Mangaf, Block 3, Street 14',
      amount_due: 21.0,
      payment_method: 'card',
      status: 'failed',
      failure_reason: 'customer_unavailable',
      note: 'Called twice, no answer',
    },
  ];
}
